apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sysdig.com/v1",
          "kind": "SysdigAgent",
          "metadata": {
            "name": "sysdigagent-sample"
          },
          "spec": {
            "auditLog": {
              "auditServerPort": 7765,
              "auditServerUrl": "0.0.0.0",
              "dynamicBackend": {
                "enabled": false
              },
              "enabled": false
            },
            "clusterName": "",
            "collectorSettings": {
              "collectorHost": null,
              "collectorPort": null,
              "ssl": null,
              "sslVerifyCertificate": null
            },
            "customAppChecks": {},
            "daemonset": {
              "affinity": {
                "nodeAffinity": {
                  "requiredDuringSchedulingIgnoredDuringExecution": {
                    "nodeSelectorTerms": [
                      {
                        "matchExpressions": [
                          {
                            "key": "kubernetes.io/arch",
                            "operator": "In",
                            "values": [
                              "amd64"
                            ]
                          },
                          {
                            "key": "kubernetes.io/os",
                            "operator": "In",
                            "values": [
                              "linux"
                            ]
                          }
                        ]
                      },
                      {
                        "matchExpressions": [
                          {
                            "key": "beta.kubernetes.io/arch",
                            "operator": "In",
                            "values": [
                              "amd64"
                            ]
                          },
                          {
                            "key": "beta.kubernetes.io/os",
                            "operator": "In",
                            "values": [
                              "linux"
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
              },
              "annotations": {},
              "env": {},
              "nodeSelector": {},
              "probes": {
                "initialDelay": 90
              },
              "updateStrategy": {
                "type": "RollingUpdate"
              }
            },
            "ebpf": {
              "enabled": false,
              "settings": {
                "mountEtcVolume": true
              }
            },
            "extraVolumes": {
              "mounts": [],
              "volumes": []
            },
            "image": {
              "overrideValue": null,
              "pullPolicy": "IfNotPresent",
              "registry": "quay.io",
              "repository": "sysdig/agent",
              "tag": "12.1.1"
            },
            "leaderelection": {
              "enable": false
            },
            "nodeAnalyzer": {
              "apiEndpoint": "",
              "benchmarkRunner": {
                "image": {
                  "pullPolicy": "IfNotPresent",
                  "repository": "sysdig/compliance-benchmark-runner",
                  "tag": "1.0.6.0"
                },
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "256Mi"
                  },
                  "requests": {
                    "cpu": "150m",
                    "memory": "128Mi"
                  }
                }
              },
              "debug": false,
              "deploy": true,
              "hostAnalyzer": {
                "image": {
                  "pullPolicy": "IfNotPresent",
                  "repository": "sysdig/host-analyzer",
                  "tag": "0.1.3"
                },
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "1536Mi"
                  },
                  "requests": {
                    "cpu": "150m",
                    "memory": "512Mi"
                  }
                },
                "schedule": "@dailydefault"
              },
              "httpProxy": null,
              "httpsProxy": null,
              "imageAnalyzer": {
                "extraVolumes": {
                  "mounts": [],
                  "volumes": []
                },
                "image": {
                  "pullPolicy": "IfNotPresent",
                  "repository": "sysdig/node-image-analyzer",
                  "tag": "0.1.15"
                },
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "1536Mi"
                  },
                  "requests": {
                    "cpu": "150m",
                    "memory": "512Mi"
                  }
                }
              },
              "noProxy": null,
              "priorityClassName": null,
              "tolerations": [
                {
                  "effect": "NoSchedule",
                  "key": "node-role.kubernetes.io/master"
                }
              ]
            },
            "nodeImageAnalyzer": {
              "affinity": {
                "nodeAffinity": {
                  "requiredDuringSchedulingIgnoredDuringExecution": {
                    "nodeSelectorTerms": [
                      {
                        "matchExpressions": [
                          {
                            "key": "kubernetes.io/arch",
                            "operator": "In",
                            "values": [
                              "amd64"
                            ]
                          },
                          {
                            "key": "kubernetes.io/os",
                            "operator": "In",
                            "values": [
                              "linux"
                            ]
                          }
                        ]
                      },
                      {
                        "matchExpressions": [
                          {
                            "key": "beta.kubernetes.io/arch",
                            "operator": "In",
                            "values": [
                              "amd64"
                            ]
                          },
                          {
                            "key": "beta.kubernetes.io/os",
                            "operator": "In",
                            "values": [
                              "linux"
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
              },
              "deploy": false,
              "extraVolumes": {
                "mounts": [],
                "volumes": []
              },
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "sysdig/node-image-analyzer",
                "tag": "0.1.15"
              },
              "priorityClassName": null,
              "resources": {
                "limits": {
                  "cpu": "500m",
                  "memory": "1024Mi"
                },
                "requests": {
                  "cpu": "250m",
                  "memory": "512Mi"
                }
              },
              "settings": {
                "debug": false,
                "httpProxy": null,
                "httpsProxy": null,
                "noProxy": null
              },
              "tolerations": [
                {
                  "effect": "NoSchedule",
                  "key": "node-role.kubernetes.io/master"
                }
              ]
            },
            "priorityClassName": null,
            "prometheus": {
              "file": false,
              "yaml": {}
            },
            "proxy": {
              "httpProxy": null,
              "httpsProxy": null,
              "noProxy": null
            },
            "psp": {
              "create": true
            },
            "rbac": {
              "create": true
            },
            "resourceProfile": "small",
            "scc": {
              "create": true
            },
            "secure": {
              "enabled": true
            },
            "serviceAccount": {
              "create": true,
              "name": null
            },
            "slim": {
              "enabled": false,
              "image": {
                "repository": "sysdig/agent-slim"
              },
              "kmoduleImage": {
                "repository": "sysdig/agent-kmodule"
              },
              "resources": {
                "limits": {
                  "memory": "512Mi"
                },
                "requests": {
                  "cpu": "1000m",
                  "memory": "348Mi"
                }
              }
            },
            "sysdig": {
              "accessKey": "",
              "disableCaptures": false,
              "existingAccessKeySecret": "",
              "settings": {}
            },
            "timezone": null,
            "tolerations": [
              {
                "effect": "NoSchedule",
                "key": "node-role.kubernetes.io/master"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: sysdig-operator.v1.12.40
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: SysdigAgent
      name: sysdigagents.sysdig.com
      version: v1
  description: Sysdig is a unified platform for container and microservices monitoring,
    troubleshooting, security and forensics. Sysdig platform has been built on top
    of Sysdig tool and Sysdig Inspect open-source technologies.
  displayName: Sysdig Agent Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - sysdig.com
          resources:
          - sysdigagents
          - sysdigagents/status
          - sysdigagents/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: sysdig-operator-controller-manager
      deployments:
      - name: sysdig-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=sysdig-operator
                image: scan.connect.redhat.com/ospid-2953a149-0b38-4515-9768-dd548c234edb/sysdig-operator:1.12.40
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              securityContext:
                runAsNonRoot: true
              serviceAccountName: sysdig-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: sysdig-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - security
  - alerting
  - metrics
  - troubleshooting
  - run-time
  - syscall
  links:
  - name: Sysdig Operator
    url: https://sysdig-operator.domain
  maintainers:
  - email: nestor.salceda@sysdig.com
    name: NÃ©stor Salceda
  - email: ashwin.chandrasekar@sysdig.com
    name: Ashwin Chandrasekar
  maturity: alpha
  provider:
    name: Sysdig
    url: https://sysdig.com
  version: 1.12.40
